{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.baihufox3210.gfl",
    "module": "gfl",
    "version": "2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gfl-2.0.2.jar",
          "url": "gfl-2.0.2.jar",
          "size": 30726,
          "sha512": "397de1fad91f0b86077c8e7e5738c3ff96b252426d9add34a19a64a75dfa9985bfd11023830784a923f9e82d381bb8b6bf300811fece24463c08d21cf45d9b4b",
          "sha256": "01c1e2391264e1fb3c3da93faf29547c81e8a9996247a70e26a1f9bf0d263b16",
          "sha1": "a8cd5808afae9c96b4231a58fe0dce886fd2a706",
          "md5": "67aaccebef937b4ce107473890f92992"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gfl-2.0.2.jar",
          "url": "gfl-2.0.2.jar",
          "size": 30726,
          "sha512": "397de1fad91f0b86077c8e7e5738c3ff96b252426d9add34a19a64a75dfa9985bfd11023830784a923f9e82d381bb8b6bf300811fece24463c08d21cf45d9b4b",
          "sha256": "01c1e2391264e1fb3c3da93faf29547c81e8a9996247a70e26a1f9bf0d263b16",
          "sha1": "a8cd5808afae9c96b4231a58fe0dce886fd2a706",
          "md5": "67aaccebef937b4ce107473890f92992"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gfl-2.0.2-sources.jar",
          "url": "gfl-2.0.2-sources.jar",
          "size": 13468,
          "sha512": "1264357a84513919950e96b4a8d6a60d46a8eacb9232d7396fc1e1ee08dac4d6b56d03a56821484192f7391d4f136d3ea0f271ecbc40a6a05d42778096e9ba74",
          "sha256": "6994cd3a1f6a9c45e56cca08d2259d51e9e4b58cec6cdf36932a5da61cffb434",
          "sha1": "38c38ca0e3129abc79d833beecf18d61f93a1695",
          "md5": "7409494995e873d1869ee0353b5a5c6d"
        }
      ]
    }
  ]
}
