{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.baihufox3210.gfl",
    "module": "gfl",
    "version": "2.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gfl-2.0.4.jar",
          "url": "gfl-2.0.4.jar",
          "size": 34033,
          "sha512": "254c0ce06ea09b8cb2e01aa00ae2d004b543c255da2247a1fd4bcd963c41d834007b3f1afaf00e72f8530b5c70930302333cc5a4ee12c928c9054e9ea16aea1b",
          "sha256": "7f89f0cfb118a57eecd47a1a4d4d827c1ffad280ef8a83f214bb1311b126b0c5",
          "sha1": "d3658e2d1fb6736fbe904afe16538cdbbf3ed519",
          "md5": "b0700d16c1bdcc5bb63050aa5d42e2c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gfl-2.0.4.jar",
          "url": "gfl-2.0.4.jar",
          "size": 34033,
          "sha512": "254c0ce06ea09b8cb2e01aa00ae2d004b543c255da2247a1fd4bcd963c41d834007b3f1afaf00e72f8530b5c70930302333cc5a4ee12c928c9054e9ea16aea1b",
          "sha256": "7f89f0cfb118a57eecd47a1a4d4d827c1ffad280ef8a83f214bb1311b126b0c5",
          "sha1": "d3658e2d1fb6736fbe904afe16538cdbbf3ed519",
          "md5": "b0700d16c1bdcc5bb63050aa5d42e2c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gfl-2.0.4-sources.jar",
          "url": "gfl-2.0.4-sources.jar",
          "size": 14958,
          "sha512": "039695a388d844592d7e0bbdb9b343cff57955b028e2cceccd45975c88ae46db7a1393b1b380cc3c294e652d93c0c08dbdc71b0a4169de4cf51455a01afc2bfc",
          "sha256": "6f1498539f09380947b46267911eed5be7f648ee1e4d955714e048b4aaee3dc7",
          "sha1": "b5e5172b13fbc9c92aa272566da8fe7be4d96946",
          "md5": "b291c96da6633c24044cb3dae5b5de14"
        }
      ]
    }
  ]
}
