{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.baihufox3210.gfl",
    "module": "gfl",
    "version": "2.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gfl-2.0.4.jar",
          "url": "gfl-2.0.4.jar",
          "size": 31182,
          "sha512": "2d5bd56b5e169325cd7042f199c6c9111f2ab03384dd542abc7b05f2c7763732ba4325c161031d5322f7082ea108244c8280557511c14ff60b0a841e7605227f",
          "sha256": "e9f616349181ab5844ac883f01569d427a2060d9c573727000d103ab8e4d0f35",
          "sha1": "f0b1865b2b8fe733e1ad3c8083d39ccdf658e3dd",
          "md5": "e0939364290163b04fb754294f1c762f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gfl-2.0.4.jar",
          "url": "gfl-2.0.4.jar",
          "size": 31182,
          "sha512": "2d5bd56b5e169325cd7042f199c6c9111f2ab03384dd542abc7b05f2c7763732ba4325c161031d5322f7082ea108244c8280557511c14ff60b0a841e7605227f",
          "sha256": "e9f616349181ab5844ac883f01569d427a2060d9c573727000d103ab8e4d0f35",
          "sha1": "f0b1865b2b8fe733e1ad3c8083d39ccdf658e3dd",
          "md5": "e0939364290163b04fb754294f1c762f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gfl-2.0.4-sources.jar",
          "url": "gfl-2.0.4-sources.jar",
          "size": 13695,
          "sha512": "4b356cfca350e6ba72636abb0b22b839d8c687101df8cf29fb93636fdd31f5078425ada518ca8b8c30fb0ab1f00d0a5d318b51381ae22a90de28652dea443cbc",
          "sha256": "f0d99ee41dfcf86b55cc4080bf8cfd08e5243c367eed2bcb6d61512efb5aaadf",
          "sha1": "02c91635d74a10f2913397947553c06ff42f9023",
          "md5": "b0cc1c80982fcde3ff42225da37d8919"
        }
      ]
    }
  ]
}
