{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.baihufox3210.gfl",
    "module": "gfl",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gfl-2.0.1.jar",
          "url": "gfl-2.0.1.jar",
          "size": 30625,
          "sha512": "5c4d2f8ec56f8d41b6c74088b8e1103bfc5d000871b782505945957c34a129b5e1de077062f9f0793cdb1b71d0b1a09db28b546bbf1a977dd0623ac3de04d87e",
          "sha256": "9cc15cc0748cbcef0a62e2db9e22e66f96d2f7067263d0956bfb19aa00c85a86",
          "sha1": "c281aba169199aac91a8101422daa2e5fd9863d9",
          "md5": "59a887dab3a3d7086d5b2e07c446d3d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gfl-2.0.1.jar",
          "url": "gfl-2.0.1.jar",
          "size": 30625,
          "sha512": "5c4d2f8ec56f8d41b6c74088b8e1103bfc5d000871b782505945957c34a129b5e1de077062f9f0793cdb1b71d0b1a09db28b546bbf1a977dd0623ac3de04d87e",
          "sha256": "9cc15cc0748cbcef0a62e2db9e22e66f96d2f7067263d0956bfb19aa00c85a86",
          "sha1": "c281aba169199aac91a8101422daa2e5fd9863d9",
          "md5": "59a887dab3a3d7086d5b2e07c446d3d7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gfl-2.0.1-sources.jar",
          "url": "gfl-2.0.1-sources.jar",
          "size": 13429,
          "sha512": "0562d27fe090a7f0f696bd517eb2372a092792b70b3e9339ffdbec9c1e2f3c3b3a4662d8ae7f8f1cabd52ff82d51e6549044dda84cb4e2a0340da82035f31ad6",
          "sha256": "ab4c5d6c630355a9aa04a2c6b8e31b8270485779dd057ba3d0d805838089cb26",
          "sha1": "3bc6709c7226beb39ceda7b3445db6cceae0a26f",
          "md5": "7c0011b62018a17bd988bae8b12470d4"
        }
      ]
    }
  ]
}
