{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.baihufox3210.gfl",
    "module": "gfl",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gfl-1.0.2.jar",
          "url": "gfl-1.0.2.jar",
          "size": 25784,
          "sha512": "98ae796ad99644bcf64b30fadb241da8897f4eb56d2bb47076d839dca594f5698c8748c5dd6c5256785a16795293b98c5e9fa48d4dbd6b5facdb542750bf9052",
          "sha256": "92ce3ba75c8e3fbf3f2542d1e484782c238106aadfbf9058fe71e95939a307d7",
          "sha1": "b8dec2d29215bdbe94d6028a291bc05ff2df7321",
          "md5": "67012535c44558fba523fb6ffafa19f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gfl-1.0.2.jar",
          "url": "gfl-1.0.2.jar",
          "size": 25784,
          "sha512": "98ae796ad99644bcf64b30fadb241da8897f4eb56d2bb47076d839dca594f5698c8748c5dd6c5256785a16795293b98c5e9fa48d4dbd6b5facdb542750bf9052",
          "sha256": "92ce3ba75c8e3fbf3f2542d1e484782c238106aadfbf9058fe71e95939a307d7",
          "sha1": "b8dec2d29215bdbe94d6028a291bc05ff2df7321",
          "md5": "67012535c44558fba523fb6ffafa19f4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gfl-1.0.2-sources.jar",
          "url": "gfl-1.0.2-sources.jar",
          "size": 11290,
          "sha512": "f30f8b3711ff137f6935c7094d656ab9e2aacad6a5b7c0ba7b2801bcc4b6414e7525d3461e1cdb985fdb7c1a138dadc8b250bdc8d7eaa8e61a21e0c42ceee4c4",
          "sha256": "7963a02cc945d677f131f15aa9f83c58b22f692088b28a094f5f4f1c365a2ae2",
          "sha1": "6d443a43cc6dc9d54ede75bf35bc9b617ef4f3c4",
          "md5": "41e2f9539fadae1794b03cb8c5beeadf"
        }
      ]
    }
  ]
}
