{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.baihufox3210.gfl",
    "module": "gfl",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gfl-2.0.0.jar",
          "url": "gfl-2.0.0.jar",
          "size": 30656,
          "sha512": "6dbd33197f354cf1ece4362c134a637cbffd5cb44e9b7e8213937285f5f64a58bfa93162688e0dae4000f66a58560e4d2cddeed94dc54b32a72b89ea114fd14e",
          "sha256": "79c85480a5fc68011c2532f9ed5f4c5a82b63e9feda7801427dba51cc7723462",
          "sha1": "7e7274a3888fe36b17f421d56cdcc629568ce917",
          "md5": "0bfdc24408d635b9bde6d79cdc9fa4e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gfl-2.0.0.jar",
          "url": "gfl-2.0.0.jar",
          "size": 30656,
          "sha512": "6dbd33197f354cf1ece4362c134a637cbffd5cb44e9b7e8213937285f5f64a58bfa93162688e0dae4000f66a58560e4d2cddeed94dc54b32a72b89ea114fd14e",
          "sha256": "79c85480a5fc68011c2532f9ed5f4c5a82b63e9feda7801427dba51cc7723462",
          "sha1": "7e7274a3888fe36b17f421d56cdcc629568ce917",
          "md5": "0bfdc24408d635b9bde6d79cdc9fa4e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gfl-2.0.0-sources.jar",
          "url": "gfl-2.0.0-sources.jar",
          "size": 13439,
          "sha512": "151860a8f4f3583d5ba1c62f510007fc4d2e093744a0a1f78145e7a6815fc28343d5989998ed57a655634b39764b91b1d99a5b109c749159aacf8f9ed84f97aa",
          "sha256": "7f2bf36bce0e51b5db4e1f2eb7a9b71001710840a5f00905fba03368f254f5fc",
          "sha1": "a12c5c462f911780b1a102d0411862726d64926f",
          "md5": "16f4ddf5a67daa050793d4e326dd0104"
        }
      ]
    }
  ]
}
