{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.baihufox3210.gfl",
    "module": "gfl",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gfl-1.1.0.jar",
          "url": "gfl-1.1.0.jar",
          "size": 25782,
          "sha512": "3de3eb381cc654af2f1cda76e91253edd5b49085590170d21685397399f97ccac6fa4b3bfe67b701ef11444c0aa67cfcbbc9d8e41fc2b56aba9ec0296c3298b7",
          "sha256": "255a81b40779f3317c717f3f85d4ae12abb87748fcf2ac10b0858720d033b339",
          "sha1": "4e31e1b807d416284fdbd1238cc0b6f3290dbf87",
          "md5": "62e2dd035d869b314a1167183b42550b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gfl-1.1.0.jar",
          "url": "gfl-1.1.0.jar",
          "size": 25782,
          "sha512": "3de3eb381cc654af2f1cda76e91253edd5b49085590170d21685397399f97ccac6fa4b3bfe67b701ef11444c0aa67cfcbbc9d8e41fc2b56aba9ec0296c3298b7",
          "sha256": "255a81b40779f3317c717f3f85d4ae12abb87748fcf2ac10b0858720d033b339",
          "sha1": "4e31e1b807d416284fdbd1238cc0b6f3290dbf87",
          "md5": "62e2dd035d869b314a1167183b42550b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gfl-1.1.0-sources.jar",
          "url": "gfl-1.1.0-sources.jar",
          "size": 11290,
          "sha512": "5da0af0baafca6179f194bfa8546ef130ae54e2081ecd9388a68b8758463c8c63038355ab8bcf405d7f3692ac2f411279f0c91b2fc04934f3fdf78b2336c0319",
          "sha256": "83c86ecd9604c4415bc8fed1fa91214f3db69eb166052eff5ad825e02b80ded5",
          "sha1": "59ced591e7e078efe8c9277c6e9a5823830296ce",
          "md5": "fafda029516c27a94e56649d6ba1675e"
        }
      ]
    }
  ]
}
