{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.baihufox3210.gfl",
    "module": "gfl",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gfl-1.1.0.jar",
          "url": "gfl-1.1.0.jar",
          "size": 25782,
          "sha512": "6b403c00624a6678060c0052da76689538a68bec01c51319ed020e91737d23727da92ccd8530b0706b4e2e9c41733f01d84420d887564e800f77735ce012fb93",
          "sha256": "de7e9369c12be7dde8983c851b29e542279dde29715f2bb993a4d5ec7cbf48e7",
          "sha1": "5f82d89643cf5aee164b547cde8fc1a7aa446170",
          "md5": "729d236b20694cc977a987dd048f2be2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gfl-1.1.0.jar",
          "url": "gfl-1.1.0.jar",
          "size": 25782,
          "sha512": "6b403c00624a6678060c0052da76689538a68bec01c51319ed020e91737d23727da92ccd8530b0706b4e2e9c41733f01d84420d887564e800f77735ce012fb93",
          "sha256": "de7e9369c12be7dde8983c851b29e542279dde29715f2bb993a4d5ec7cbf48e7",
          "sha1": "5f82d89643cf5aee164b547cde8fc1a7aa446170",
          "md5": "729d236b20694cc977a987dd048f2be2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gfl-1.1.0-sources.jar",
          "url": "gfl-1.1.0-sources.jar",
          "size": 11290,
          "sha512": "f13c2098b7d691b0d07cdca6fc68693cdad6e189792e3cce2a868527d97b2ff883bec85088853b9054cd4742d51e0aff0c677ca56ebfa2220da9d69efd4dd939",
          "sha256": "b69885b3a3df52a618273ab9323b2c4299397692d61be462703bfb0726cda1bd",
          "sha1": "f892f304f597eced7a7cddde8ea7778401154aab",
          "md5": "9b2afdd310934844ba1486eb11bfaa31"
        }
      ]
    }
  ]
}
