{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.baihufox3210.gfl",
    "module": "gfl",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gfl-1.1.0.jar",
          "url": "gfl-1.1.0.jar",
          "size": 25782,
          "sha512": "e0f0d9b67d8937abc9075379d5a08b4207531c28f2eaf1f2a45c98898872c60b1ce022b542f9e1191ff538d85edc38f21b43034c3233a739fa51f9d1fb011673",
          "sha256": "407da61abfddd585c41ac42483ff684fcd8650a4d4e2f0662fd1d49110a7086f",
          "sha1": "38b81a9ebb9a166d2b4ae659897d2a3a6b3b52ff",
          "md5": "191225da90305dc655d718e99c0c7dbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gfl-1.1.0.jar",
          "url": "gfl-1.1.0.jar",
          "size": 25782,
          "sha512": "e0f0d9b67d8937abc9075379d5a08b4207531c28f2eaf1f2a45c98898872c60b1ce022b542f9e1191ff538d85edc38f21b43034c3233a739fa51f9d1fb011673",
          "sha256": "407da61abfddd585c41ac42483ff684fcd8650a4d4e2f0662fd1d49110a7086f",
          "sha1": "38b81a9ebb9a166d2b4ae659897d2a3a6b3b52ff",
          "md5": "191225da90305dc655d718e99c0c7dbe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gfl-1.1.0-sources.jar",
          "url": "gfl-1.1.0-sources.jar",
          "size": 11290,
          "sha512": "e023acbadc2f543213902e33cc53a178bf1526c125a6767389114d09820ee6e87fa88b388351748c5baa743d8776514422ef450f4c91b9700baa54546ef0cf5e",
          "sha256": "9653b9f6e2c967f9da0bf6e69a4d60c24666ebee2fd9fcb32624064e7a38ccf8",
          "sha1": "2f73e8f221624a98148f11b8b762490258c0df85",
          "md5": "bc14413c6793a01a1ed41d6f7d6a1c36"
        }
      ]
    }
  ]
}
