{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.baihufox3210.gfl",
    "module": "gfl",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gfl-3.0.0.jar",
          "url": "gfl-3.0.0.jar",
          "size": 34031,
          "sha512": "85dfda4ced62a3f7c0807630cc30b26a3f7f85c1d0132ea5d4ff67a494765aea6198510f8412636d1cc3153e13805d286aa5930041b1ca0f0a381adb079e5d59",
          "sha256": "d00fed18b841771b2f3729d04b4b817b3c3c359a101857af13eb1ee6a496b3c7",
          "sha1": "f5e4dcc404936cac77d8d1d4c26f15a12bde80a5",
          "md5": "c07ef2e82b0d610eb2ec2ee0302822ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gfl-3.0.0.jar",
          "url": "gfl-3.0.0.jar",
          "size": 34031,
          "sha512": "85dfda4ced62a3f7c0807630cc30b26a3f7f85c1d0132ea5d4ff67a494765aea6198510f8412636d1cc3153e13805d286aa5930041b1ca0f0a381adb079e5d59",
          "sha256": "d00fed18b841771b2f3729d04b4b817b3c3c359a101857af13eb1ee6a496b3c7",
          "sha1": "f5e4dcc404936cac77d8d1d4c26f15a12bde80a5",
          "md5": "c07ef2e82b0d610eb2ec2ee0302822ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gfl-3.0.0-sources.jar",
          "url": "gfl-3.0.0-sources.jar",
          "size": 14958,
          "sha512": "9175bcea101a5a85b70337692abf49960f2bf6f6c443676e228a154c3a40aa0f7a29f11b85534b1166c8946a5ca44bbe549928d6cb140c0512fa5931af9829c4",
          "sha256": "a774013e70c5dfd68bf2b770d553b47d173cebfcba51147066d024f76aae0ea7",
          "sha1": "d3e7531790ff45d96274ad94e946ad137d4ea9dd",
          "md5": "a75ced3a4e2351c48f39c3829f147a09"
        }
      ]
    }
  ]
}
